/**
 * QuorumUX — Core Type Definitions
 *
 * These types define the contract between pipeline stages and project configurations.
 */

// ─── Project Configuration ───────────────────────────────────────────────────

export interface QuorumUXConfig {
  /** Project display name */
  name: string;

  /** One-line description used in AI system prompts */
  description: string;

  /** Domain category (e.g., "career-tech", "fintech", "healthcare") */
  domain: string;

  /** Production URL of the application under test */
  appUrl: string;

  /** High-level user journey description for AI context */
  userJourney: string;

  /** Where test artifacts are stored */
  artifactsDir: string;

  /** Model configuration */
  models: ModelConfig;

  /** Optional: custom system prompt additions for analysis */
  analysisContext?: string;

  /** Optional: custom system prompt additions for synthesis */
  synthesisContext?: string;

  /** Optional: video analysis settings */
  video?: VideoConfig;

  /** Optional: persona archetype IDs selected for this project */
  personas?: string[];
}

export interface ModelConfig {
  /** Models used for screenshot analysis (Stage 2) */
  screenshot: ModelSpec[];

  /** Model used for video temporal analysis (Stage 2b) */
  video: ModelSpec;

  /** Model used for cross-model synthesis (Stage 3) */
  synthesis: ModelSpec;
}

export interface ModelSpec {
  /** OpenRouter model ID (e.g., "anthropic/claude-sonnet-4.6") */
  id: string;

  /** Short name for display and JSON keys (e.g., "claude", "gemini") */
  name: string;

  /** Optional: max tokens for response */
  maxTokens?: number;
}

export interface VideoConfig {
  /** Max video file size in MB before skipping (default: 20) */
  maxSizeMB?: number;

  /** Frame extraction rate in fps (default: 1) */
  frameRate?: number;
}

// ─── Artifacts & Directory Structure ─────────────────────────────────────────

/**
 * Expected artifact directory structure:
 *
 * {artifactsDir}/{runId}/
 * ├── videos/{personaId}/{hash}.webm
 * ├── screenshots/{personaId}/{personaId}-step{NN}-{VERDICT}-{label}.png
 * ├── summaries/{personaId}-summary.json
 * ├── executive-summary.md
 * ├── frames/{personaId}/frame-{NNNN}.jpg       (generated by Stage 1)
 * ├── grids/{personaId}-grid.jpg                  (generated by Stage 1)
 * ├── diffs/{personaId}/diff-*.png                (generated by Stage 1)
 * └── reports/
 *     ├── all-analyses-raw.json                   (generated by Stage 2)
 *     ├── all-video-analyses-raw.json             (generated by Stage 2b)
 *     ├── synthesis.json                          (generated by Stage 3)
 *     ├── ux-analysis-report.md                   (generated by Stage 4)
 *     └── github-issues.md                        (generated by Stage 4)
 */

export interface RunArtifacts {
  runId: string;
  runDir: string;
  videosDir: string;
  screenshotsDir: string;
  summariesDir: string;
  framesDir: string;
  gridsDir: string;
  diffsDir: string;
  reportsDir: string;
}

// ─── Persona Summary (Input from Test Runner) ────────────────────────────────

export interface PersonaSummary {
  runId: string;
  persona: string;
  personaId: string;
  timestamp: string;
  totalSteps: number;
  results: {
    pass: number;
    friction: number;
    fail: number;
  };
  issues: PersonaIssue[];
  flowScores: Record<string, number>;
  retentionAssessment: string;
  topFrictionPoint: string;
  topDelight: string;
}

export interface PersonaIssue {
  id: string;
  step: number;
  severity: 'FAIL' | 'FRICTION';
  category: IssueCategory;
  description: string;
  expected: string;
  screenshotPath?: string;
  videoTimestamp?: string;
}

export type IssueCategory =
  | 'Function'
  | 'UX'
  | 'Copy'
  | 'Visual'
  | 'Performance'
  | 'Accessibility';

export type Verdict = 'PASS' | 'FRICTION' | 'FAIL';

// ─── Analysis Results (Stage 2 + 2b Output) ─────────────────────────────────

export interface ScreenshotAnalysis {
  persona: string;
  model: string;
  modelId: string;
  analysis: string;
  error?: string;
  tokens?: {
    prompt: number;
    completion: number;
    total: number;
  };
}

export interface VideoAnalysis {
  persona: string;
  model: string;
  modelId: string;
  analysisType: 'video';
  videoPath: string;
  videoSizeMB: number;
  analysis: string;
  error?: string;
}

// ─── Synthesis Output (Stage 3) ──────────────────────────────────────────────

export interface Synthesis {
  synthesisDate: string;
  projectName: string;
  sourceCounts: {
    screenshotAnalyses: number;
    videoAnalyses: number;
    testSummaries: number;
  };
  consensusIssues: ConsensusIssue[];
  videoOnlyIssues: VideoOnlyIssue[];
  modelUniqueIssues: ModelUniqueIssue[];
  disagreements: Disagreement[];
  overallAssessment: OverallAssessment;
}

export interface ConsensusIssue {
  id: string;
  title: string;
  severity: 'P0' | 'P1' | 'P2';
  category: string;
  description: string;
  evidence: {
    screenshotModels: string[];
    videoConfirmed: boolean;
    testRunConfirmed: boolean;
    affectedPersonas: string[];
  };
  temporalInsight: string | null;
  recommendation: string;
  effort: 'low' | 'medium' | 'high';
  /** Issue source: "app" (real product issue) or "test-infra" (test automation problem) */
  source?: 'app' | 'test-infra';
  /** Ordinal display counter (replaces model-generated sequential IDs) */
  index?: number;
}

export interface VideoOnlyIssue {
  id: string;
  title: string;
  severity: 'P0' | 'P1' | 'P2';
  description: string;
  timestamp: string;
  persona: string;
  recommendation: string;
  source?: 'app' | 'test-infra';
  index?: number;
}

export interface ModelUniqueIssue {
  id: string;
  title: string;
  reportedBy: string;
  severity: 'P0' | 'P1' | 'P2';
  description: string;
  recommendation: string;
  confidence: 'low' | 'medium' | 'high';
  source?: 'app' | 'test-infra';
  index?: number;
}

export interface Disagreement {
  topic: string;
  positions: Record<string, string>;
  recommendation: string;
}

export interface OverallAssessment {
  uxScore: number;
  launchReadiness: 'ready' | 'ready-with-caveats' | 'not-ready';
  topStrengths: string[];
  criticalPath: string[];
  temporalInsightsSummary: string;
}

// ─── Persona Archetypes ─────────────────────────────────────────────────────

export interface PersonaArchetype {
  id: string;
  name: string;
  description: string;
  device: 'desktop' | 'mobile' | 'tablet';
  viewport: { width: number; height: number };
  behaviorNotes: string;
  accessibilityNeeds?: string[];
}

// ─── Global Config (~/.quorumux/config.json) ──────────────────────────────────

export interface GlobalConfig {
  apiKey?: string;
  defaultModels?: ModelConfig;
  projects?: Record<string, unknown>;
}

// ─── Report JSON Output ───────────────────────────────────────────────────────

export interface ReportJSONIssue {
  type: 'consensus' | 'video-only' | 'model-unique';
  id: string;
  title: string;
  severity: 'P0' | 'P1' | 'P2';
  description: string;
  recommendation: string;
  /** Only present for consensus issues */
  category?: string;
  effort?: 'low' | 'medium' | 'high';
  evidence?: ConsensusIssue['evidence'];
  temporalInsight?: string | null;
  /** Only present for video-only issues */
  timestamp?: string;
  persona?: string;
  /** Only present for model-unique issues */
  reportedBy?: string;
  confidence?: 'low' | 'medium' | 'high';
  /** Issue source classification */
  source?: 'app' | 'test-infra';
  /** Ordinal display counter */
  index?: number;
}

export interface ReportJSON {
  runId: string;
  generatedAt: string;
  projectName: string;
  score: number;
  /** Adjusted score with test-infra issues discounted (undefined if no test-infra issues) */
  adjustedScore?: number;
  launchReadiness: 'ready' | 'ready-with-caveats' | 'not-ready';
  issueCount: number;
  issues: ReportJSONIssue[];
  models: string[];
  personas: string[];
  topStrengths: string[];
  criticalPath: string[];
}

// ─── CLI Options ─────────────────────────────────────────────────────────────

export interface PipelineOptions {
  /** Path to quorumux.config.ts */
  config: string;

  /** Specific run directory (auto-detects latest if omitted) */
  runDir?: string;

  /** Stage to start from (1-4, default: 1) */
  startStage?: number;

  /** Only run specific stages */
  stages?: number[];

  /** Skip video analysis */
  skipVideo?: boolean;

  /** Verbose logging */
  verbose?: boolean;

  /** Dry run: show what would run without making API calls */
  dryRun?: boolean;

  /** Override output directory for reports (default: {runDir}/reports/) */
  outputDir?: string;
}
